/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tagabukid.hrmis.pmis.views;

/**
 *
 * @author rufino
 */
public class MasterSuccessIndicatorListQueryForm extends javax.swing.JPanel {

    /**
     * Creates new form TagabukidSubayListQueryForm
     */
    public MasterSuccessIndicatorListQueryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xActionTextField2 = new com.rameses.rcp.control.XActionTextField();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        xFormPanel1.setAddCaptionColon(false);
        xFormPanel1.setCaptionBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        xFormPanel1.setCaptionFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        xFormPanel1.setCaptionForeground(new java.awt.Color(80, 80, 80));
        xFormPanel1.setCaptionPadding(new java.awt.Insets(0, 5, 0, 5));
        xFormPanel1.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xFormPanel1.setCaptionWidth(0);
        xFormPanel1.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);

        xLookupField1.setCaption("Org/ Office");
        xLookupField1.setCaptionWidth(80);
        xLookupField1.setExpression("#{params.org.Entity.Name}");
        xLookupField1.setHandler("lookupOrg");
        xLookupField1.setHint("Select Org/Office");
        xLookupField1.setName("params.org"); // NOI18N
        xLookupField1.setPreferredSize(new java.awt.Dimension(300, 22));
        xFormPanel1.add(xLookupField1);

        xActionTextField2.setActionName("search");
        xActionTextField2.setCaption("Search");
        xActionTextField2.setCaptionWidth(55);
        xActionTextField2.setFocusAccelerator('s');
        xActionTextField2.setFocusKeyStroke("F3");
        xActionTextField2.setName("params.searchtext"); // NOI18N
        xActionTextField2.setPreferredSize(new java.awt.Dimension(220, 22));
        xFormPanel1.add(xActionTextField2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xFormPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XActionTextField xActionTextField2;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    // End of variables declaration//GEN-END:variables
}
